package diagnostics

import (
	"go/ast"
	"go/parser"
	"go/token"
	"testing"

	"golang.org/x/tools/go/analysis"
)

func TestExcludeGeneratedPreservesInputsAndResults(t *testing.T) {
	t.Parallel()

	fset := token.NewFileSet()
	generated := parseFile(t, fset, "generated.go", `// Code generated by test. DO NOT EDIT.
package example
`)
	ordinary := parseFile(t, fset, "ordinary.go", `package example
`)

	analyzer := &analysis.Analyzer{
		Name: "probe",
		Doc:  "reports each input and returns their count",
		Run: func(pass *analysis.Pass) (any, error) {
			for _, file := range pass.Files {
				pass.Reportf(file.Pos(), "input")
			}
			return len(pass.Files), nil
		},
	}
	ExcludeGenerated(analyzer)

	var reported []analysis.Diagnostic
	pass := &analysis.Pass{
		Analyzer: analyzer,
		Fset:     fset,
		Files:    []*ast.File{generated, ordinary},
		Report: func(diagnostic analysis.Diagnostic) {
			reported = append(reported, diagnostic)
		},
	}
	result, err := analyzer.Run(pass)
	if err != nil {
		t.Fatal(err)
	}
	if result != 2 {
		t.Fatalf("result = %v, want both analyzer inputs", result)
	}
	if len(reported) != 1 || reported[0].Pos != ordinary.Pos() {
		t.Fatalf("reported diagnostics = %#v, want only ordinary.go", reported)
	}
}

func parseFile(t *testing.T, fset *token.FileSet, name, source string) *ast.File {
	t.Helper()
	file, err := parser.ParseFile(fset, name, source, parser.ParseComments)
	if err != nil {
		t.Fatal(err)
	}
	return file
}
