name: Go

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - name: Set up go
          uses: actions/setup-go@v5
        - name: Build
          run: go build -v ./...
        - name: Test
          run: go test -v ./...
        - name: Vet
          run: go vet ./...
        - name: Lint
          run: go run ./cmd/glint ./...
